import { describe, it, expect } from 'vitest';
import { parsePly } from './ply-parser.js';

/** 生成一个最小化二进制 PLY (单顶点, position only) */
function makeBinaryPly(): ArrayBuffer {
  const header =
    'ply\nformat binary_little_endian 1.0\nelement vertex 1\n' +
    'property float x\nproperty float y\nproperty float z\nend_header\n';
  const headerBytes = new TextEncoder().encode(header);
  const body = new Float32Array([1.0, 2.0, 3.0]);
  const buffer = new ArrayBuffer(headerBytes.length + body.byteLength);
  new Uint8Array(buffer).set(headerBytes, 0);
  new Uint8Array(buffer).set(new Uint8Array(body.buffer), headerBytes.length);
  return buffer;
}

/** 生成一个 ASCII PLY */
function makeAsciiPly(): string {
  return (
    'ply\nformat ascii 1.0\n' +
    'element vertex 2\n' +
    'property float x\nproperty float y\nproperty float z\n' +
    'property uchar red\nproperty uchar green\nproperty uchar blue\n' +
    'end_header\n' +
    '1.0 2.0 3.0 255 0 0\n' +
    '4.0 5.0 6.0 0 255 0\n'
  );
}

describe('parsePly', () => {
  it('解析二进制 PLY', () => {
    const buffer = makeBinaryPly();
    const result = parsePly(buffer);

    expect(result.header.format).toBe('binary_little_endian');
    expect(result.header.elements).toHaveLength(1);
    expect(result.header.elements[0].name).toBe('vertex');
    expect(result.header.elements[0].count).toBe(1);

    const vertices = result.data.get('vertex')!;
    expect(vertices).toHaveLength(1);
    expect(Number(vertices[0].x)).toBe(1.0);
    expect(Number(vertices[0].y)).toBe(2.0);
    expect(Number(vertices[0].z)).toBe(3.0);
  });

  it('解析 ASCII PLY', () => {
    const text = makeAsciiPly();
    const buffer = new TextEncoder().encode(text).buffer;
    const result = parsePly(buffer);

    expect(result.header.format).toBe('ascii');
    const vertices = result.data.get('vertex')!;
    expect(vertices).toHaveLength(2);
    expect(Number(vertices[0].x)).toBe(1.0);
    expect(Number(vertices[0].red)).toBe(255);
    expect(Number(vertices[1].y)).toBe(5.0);
    expect(Number(vertices[1].green)).toBe(255);
  });

  it('拒绝无效 PLY (第一行不是 ply)', () => {
    const buffer = new TextEncoder().encode('not_ply\n').buffer;
    expect(() => parsePly(buffer)).toThrow(/无效的 PLY/);
  });

  it('正确解析 header 中的 comments', () => {
    const text = 'ply\nformat ascii 1.0\ncomment Generated by test\nelement vertex 0\nend_header\n';
    const buffer = new TextEncoder().encode(text).buffer;
    const result = parsePly(buffer);

    expect(result.header.comments).toContain('Generated by test');
  });
});
