import { describe, it, expect } from 'vitest';
import { parsePly, parsePlyHeader } from './ply-parser.js';
import { loadGaussiansFromPly, loadGaussiansFromPlySoA } from './gaussian-loader.js';

/** 生成一个最小化二进制 PLY (单顶点, position only) */
function makeBinaryPly(): ArrayBuffer {
  const header =
    'ply\nformat binary_little_endian 1.0\nelement vertex 1\n' +
    'property float x\nproperty float y\nproperty float z\nend_header\n';
  const headerBytes = new TextEncoder().encode(header);
  const body = new Float32Array([1.0, 2.0, 3.0]);
  const buffer = new ArrayBuffer(headerBytes.length + body.byteLength);
  new Uint8Array(buffer).set(headerBytes, 0);
  new Uint8Array(buffer).set(new Uint8Array(body.buffer), headerBytes.length);
  return buffer;
}

/** 生成一个 ASCII PLY */
function makeAsciiPly(): string {
  return (
    'ply\nformat ascii 1.0\n' +
    'element vertex 2\n' +
    'property float x\nproperty float y\nproperty float z\n' +
    'property uchar red\nproperty uchar green\nproperty uchar blue\n' +
    'end_header\n' +
    '1.0 2.0 3.0 255 0 0\n' +
    '4.0 5.0 6.0 0 255 0\n'
  );
}

describe('parsePly', () => {
  it('解析二进制 PLY', () => {
    const buffer = makeBinaryPly();
    const result = parsePly(buffer);

    expect(result.header.format).toBe('binary_little_endian');
    expect(result.header.elements).toHaveLength(1);
    expect(result.header.elements[0].name).toBe('vertex');
    expect(result.header.elements[0].count).toBe(1);

    const vertices = result.data.get('vertex')!;
    expect(vertices).toHaveLength(1);
    expect(Number(vertices[0].x)).toBe(1.0);
    expect(Number(vertices[0].y)).toBe(2.0);
    expect(Number(vertices[0].z)).toBe(3.0);
  });

  it('解析 ASCII PLY', () => {
    const text = makeAsciiPly();
    const buffer = new TextEncoder().encode(text).buffer;
    const result = parsePly(buffer);

    expect(result.header.format).toBe('ascii');
    const vertices = result.data.get('vertex')!;
    expect(vertices).toHaveLength(2);
    expect(Number(vertices[0].x)).toBe(1.0);
    expect(Number(vertices[0].red)).toBe(255);
    expect(Number(vertices[1].y)).toBe(5.0);
    expect(Number(vertices[1].green)).toBe(255);
  });

  it('拒绝无效 PLY (第一行不是 ply)', () => {
    const buffer = new TextEncoder().encode('not_ply\n').buffer;
    expect(() => parsePly(buffer)).toThrow(/无效的 PLY/);
  });

  it('正确解析 header 中的 comments', () => {
    const text = 'ply\nformat ascii 1.0\ncomment Generated by test\nelement vertex 0\nend_header\n';
    const buffer = new TextEncoder().encode(text).buffer;
    const result = parsePly(buffer);

    expect(result.header.comments).toContain('Generated by test');
  });
});

describe('parsePlyHeader CRLF 兼容', () => {
  /** 生成二进制 PLY 原始字节 (lineEnding 控制每行结尾) */
  function makePlyBytes(lineEnding: '\n' | '\r\n'): ArrayBuffer {
    const header =
      `ply${lineEnding}format binary_little_endian 1.0${lineEnding}` +
      `element vertex 1${lineEnding}` +
      `property float x${lineEnding}property float y${lineEnding}property float z${lineEnding}` +
      `end_header${lineEnding}`;
    const headerBytes = new TextEncoder().encode(header);
    const body = new Float32Array([1.0, 2.0, 3.0]);
    const buffer = new ArrayBuffer(headerBytes.length + body.byteLength);
    new Uint8Array(buffer).set(headerBytes, 0);
    new Uint8Array(buffer).set(new Uint8Array(body.buffer), headerBytes.length);
    return buffer;
  }

  it('CRLF 与 LF body 起始对齐且首个顶点位置正确', () => {
    const lf = makePlyBytes('\n');
    const crlf = makePlyBytes('\r\n');

    const lfHeader = parsePlyHeader(lf);
    const crlfHeader = parsePlyHeader(crlf);

    // CRLF 每行多 1 字节 (\r), headerEnd 精确指向 body 起始
    const lfBody = new DataView(lf, lfHeader.headerEnd);
    const crlfBody = new DataView(crlf, crlfHeader.headerEnd);
    expect(crlfBody.getFloat32(0, true)).toBe(lfBody.getFloat32(0, true));
    expect(crlfBody.getFloat32(0, true)).toBe(1.0);

    // 首个顶点位置正确 (x=1, y=2, z=3)
    const cloud = loadGaussiansFromPly(crlf);
    expect(cloud.splats).toHaveLength(1);
    expect(cloud.splats[0].x).toBe(1.0);
    expect(cloud.splats[0].y).toBe(2.0);
    expect(cloud.splats[0].z).toBe(3.0);
  });
});

describe('tryFastPathParsePly 前置 element 偏移', () => {
  /** 生成 face(list) 在 vertex 之前的二进制 PLY */
  function makePlyWithLeadingFace(): ArrayBuffer {
    const header =
      'ply\nformat binary_little_endian 1.0\n' +
      'element face 1\n' +
      'property list uchar int vertex_indices\n' +
      'element vertex 1\n' +
      'property float x\nproperty float y\nproperty float z\n' +
      'end_header\n';
    const headerBytes = new TextEncoder().encode(header);

    // body: face (uchar count=1 + int index=0) + vertex (3 floats)
    const face = new Uint8Array([1, 0, 0, 0, 0]); // count=1, int32(0)
    const vertex = new Float32Array([1.0, 2.0, 3.0]);
    const buffer = new ArrayBuffer(headerBytes.length + face.length + vertex.byteLength);
    new Uint8Array(buffer).set(headerBytes, 0);
    new Uint8Array(buffer).set(face, headerBytes.length);
    new Uint8Array(buffer).set(new Uint8Array(vertex.buffer), headerBytes.length + face.length);
    return buffer;
  }

  it('快路径与慢路径 parsePly 结果一致 (list element 前置)', () => {
    const buffer = makePlyWithLeadingFace();

    // 慢路径
    const slow = parsePly(buffer);
    const slowVertex = slow.data.get('vertex')![0];
    expect(Number(slowVertex.x)).toBe(1.0);
    expect(Number(slowVertex.y)).toBe(2.0);
    expect(Number(slowVertex.z)).toBe(3.0);

    // 快路径 AoS 与 SoA
    const cloud = loadGaussiansFromPly(buffer);
    expect(cloud.splats).toHaveLength(1);
    expect(cloud.splats[0].x).toBe(1.0);
    expect(cloud.splats[0].y).toBe(2.0);
    expect(cloud.splats[0].z).toBe(3.0);

    const soa = loadGaussiansFromPlySoA(buffer);
    expect(soa.count).toBe(1);
    expect(soa.positions[0]).toBe(1.0);
    expect(soa.positions[1]).toBe(2.0);
    expect(soa.positions[2]).toBe(3.0);
  });
});
