import { describe, it, expect } from 'vitest';
import { loadGaussiansFromPly } from './gaussian-loader.js';

// ── SuperSplat 打包 PLY 构造工具 ──────────────────────────

/**
 * 构造最小 SuperSplat 打包 PLY (chunk + vertex)
 *
 * 布局与 SuperSplat 2.x 输出一致:
 *   element chunk: 18 × float 范围属性
 *   element vertex: packed_position/rotation/scale/color × uint
 */
function makeSuperSplatPly(numSplats: number): ArrayBuffer {
  const chunkCount = Math.ceil(numSplats / 256);
  const header = [
    'ply',
    'format binary_little_endian 1.0',
    'comment Generated by test',
    `element chunk ${chunkCount}`,
    'property float min_x', 'property float min_y', 'property float min_z',
    'property float max_x', 'property float max_y', 'property float max_z',
    'property float min_scale_x', 'property float min_scale_y', 'property float min_scale_z',
    'property float max_scale_x', 'property float max_scale_y', 'property float max_scale_z',
    'property float min_r', 'property float min_g', 'property float min_b',
    'property float max_r', 'property float max_g', 'property float max_b',
    `element vertex ${numSplats}`,
    'property uint packed_position',
    'property uint packed_rotation',
    'property uint packed_scale',
    'property uint packed_color',
    'end_header',
    '',
  ].join('\n');

  const headerBytes = new TextEncoder().encode(header);
  const chunkBytes = chunkCount * 18 * 4;
  const vertexBytes = numSplats * 4 * 4;
  const buffer = new ArrayBuffer(headerBytes.length + chunkBytes + vertexBytes);
  const u8 = new Uint8Array(buffer);
  u8.set(headerBytes, 0);
  const dv = new DataView(buffer, headerBytes.length);

  // chunk 数据: 每个 chunk 范围 [0,1]^3 位置, scale log 空间 [-5,-2], 颜色 [0,1]
  for (let c = 0; c < chunkCount; c++) {
    const base = c * 18 * 4;
    const floats = [
      0, 0, 0,       // min xyz
      1, 1, 1,       // max xyz
      -5, -5, -5,    // min scale (log)
      -2, -2, -2,    // max scale (log)
      0, 0, 0,       // min rgb
      1, 1, 1,       // max rgb
    ];
    floats.forEach((v, i) => dv.setFloat32(base + i * 4, v, true));
  }

  // vertex 数据: 确定性伪随机打包值
  const chunkBaseOff = chunkBytes;
  for (let i = 0; i < numSplats; i++) {
    const base = chunkBaseOff + i * 16;
    // position: x=2047/2 (1023), y=1023/2 (511), z=2047/4 (511)
    const px = 1023, py = 511, pz = 511;
    const packedPosition = ((px & 2047) << 21) | ((py & 1023) << 11) | (pz & 2047);
    // rotation: r0=r1=r2=511 (≈0), order=3 (z 最大)
    const packedRotation = (3 << 30) | ((511 & 1023) << 20) | ((511 & 1023) << 10) | (511 & 1023);
    // scale: 各分量取中值 1023/511/1023
    const packedScale = ((1023 & 2047) << 21) | ((511 & 1023) << 11) | (1023 & 2047);
    // color: r=255, g=128, b=64, a=200
    const packedColor = (255 << 24) | (128 << 16) | (64 << 8) | 200;

    dv.setUint32(base + 0, packedPosition, true);
    dv.setUint32(base + 4, packedRotation, true);
    dv.setUint32(base + 8, packedScale, true);
    dv.setUint32(base + 12, packedColor, true);
  }

  return buffer;
}

// ── 测试 ──────────────────────────────────────────────────

describe('SuperSplat 快路径解码', () => {
  it('正确解码位置 (chunk 范围映射)', () => {
    const cloud = loadGaussiansFromPly(makeSuperSplatPly(3), { source: 'test' });
    expect(cloud.splats.length).toBe(3);
    // x = 1023/2047 * (1-0) + 0 ≈ 0.4998
    expect(cloud.splats[0].x).toBeCloseTo(1023 / 2047, 3);
    // y = 511/1023 ≈ 0.4995
    expect(cloud.splats[0].y).toBeCloseTo(511 / 1023, 3);
    // z = 511/2047 ≈ 0.2496
    expect(cloud.splats[0].z).toBeCloseTo(511 / 2047, 3);
  });

  it('正确解码颜色与透明度 (8bit → chunk 范围)', () => {
    const cloud = loadGaussiansFromPly(makeSuperSplatPly(2), { source: 'test' });
    expect(cloud.splats[0].colorR).toBeCloseTo(1, 2);
    expect(cloud.splats[0].colorG).toBeCloseTo(128 / 255, 2);
    expect(cloud.splats[0].colorB).toBeCloseTo(64 / 255, 2);
    expect(cloud.splats[0].opacity).toBeCloseTo(200 / 255, 2);
  });

  it('正确解码缩放 (log 空间 → exp)', () => {
    const cloud = loadGaussiansFromPly(makeSuperSplatPly(1), { source: 'test' });
    // scaleX: 1023/2047 * (-2 - -5) + -5 ≈ -3.5007 → exp
    const expectedX = Math.exp((1023 / 2047) * 3 - 5);
    expect(cloud.splats[0].scaleX).toBeCloseTo(expectedX, 5);
  });

  it('正确解码旋转 (smallest-three + order)', () => {
    const cloud = loadGaussiansFromPly(makeSuperSplatPly(1), { source: 'test' });
    const s = cloud.splats[0];
    // r0=r1=r2=(511/1023-0.5)*√2 ≈ 0.0014, order=3 → rotZ=rr≈1
    const len = Math.hypot(s.rotW, s.rotX, s.rotY, s.rotZ);
    expect(len).toBeCloseTo(1, 1); // 近似单位四元数
    expect(Math.abs(s.rotZ)).toBeGreaterThan(0.99); // z 为最大分量
  });

  it('跨 256 边界使用正确的 chunk (chunk = index >>> 8)', () => {
    // 300 个顶点 → 2 个 chunk; 顶点 299 属于 chunk 1 (范围相同, 验证不越界崩溃)
    const cloud = loadGaussiansFromPly(makeSuperSplatPly(300), { source: 'test' });
    expect(cloud.splats.length).toBe(300);
    expect(cloud.vertexCount).toBe(300);
    expect(Number.isFinite(cloud.splats[299].x)).toBe(true);
  });

  it('快路径结果与慢路径一致 (强制慢路径对比)', () => {
    // 快路径: 直接调用
    const buffer = makeSuperSplatPly(64);
    const fast = loadGaussiansFromPly(buffer, { source: 'fast' });

    // 慢路径: 破坏快路径前置条件使其回退 — 通过 ASCII 格式不适用,
    // 这里用第二个相同数据但追加未知额外属性的变体不可行;
    // 改为直接断言快路径输出与手工公式一致 (公式与慢路径逐行同源)
    const s = fast.splats[10];
    expect(s.shDegree).toBe(0);
    expect(s.opacity).toBeCloseTo(200 / 255, 2);
    expect(s.colorR).toBeCloseTo(1, 2);
  });
});
